######################################################################
# Automatically generated by qmake (2.01a) ?? 7? 27 16:22:05 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += yaojiang.h
FORMS += yaojiang.ui
SOURCES += main.cpp yaojiang.cpp
RESOURCES += images.qrc
